### ISSUE TITLE
JSON parser script link is broken on vscode extension page

### ISSUE THREAD

**Issue by CGMossa** [selimanac/defold-vsc-snippets#2]
The links for the python script that produces the JSON file with the API are broken.

**Comment by CGMossa** [comment]
https://github.com/selimanac/defold-vsc-snippets/blob/master/scr/defold_json_convert.py

**Comment by selimanac** [comment]
OK. I'm going to update it, thank you.

**Comment by selimanac** [comment]
I removed this link entirely. You can find this python file in `src` folder.
Also I updated the snippets:

v1.2.2

- API version 1.2.169
- Python script is updated. It is now download, unpack and parse the docs. Python script requires Python version 2.7. It may fail with Python version 3.x
